baseurl = "https://colinyates.co.uk"
languageCode = "en"
title = "Random thoughts"
theme = "anatole"
copyright = "&copy; <a href=\"https://github.com/yatesco\">Colin Yates</a>"
description = "Christian, father, husband and Software Engineer."
keywords = ["keyword1", "keyword2"]


summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[related]
includeNewer = true
threshold = 80
toLower = true
[[related.indices]]
name = 'keywords'
weight = 100
[[related.indices]]
name = 'tags'
weight = 80

[services]

[services.disqus]
shortname = 'colinyatest123'
# Google Analytics
[services.googleAnalytics]
#ID = 'G-MEASUREMENT_ID'
