baseurl = "https://colinyates.co.uk"
languageCode = "en"
title = "Random thoughts"
theme = "ananke"
#copyright = "&copy; <a href=\"https://github.com/beli3ver\">Malte Kiefer</a> 2016"
disqusShortname = "colinyates123"
googleAnalytics = ""
description = "Christian, father, husband and Software Engineer."
keywords = ["keyword1", "keyword2"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "lisp", "clojure"]

[[params.social]]
url = "/tags"
fa_icon = "fa-tags"

[[params.social]]
url = "https://github.com/yatesco"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/yatesco"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/yatescolin"
fa_icon = "fa-linkedin"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
